services:
  backend:
    build: .
    env_file:
      - .env
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
      - ./db/universityBranch.sql:/docker-entrypoint-initdb.d/universityBranch.sql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:

